package raf.dsw.gerumap.messageGenerator;

public enum EventType {
    CANT_ADD_CHILD, CANT_EMPTY_STRING, CANT_DELETE_PROJECTEXPOLORER, MUST_SELECT, CANT_RENAME_AUTHOR,
    CANT_ADD_TOPIC, CANT_ADD_LINK, MUST_SELECT_BEFORE_DELETE, MUST_SELECT_BEFORE_MOVE, MUST_SELECT_BEFORE_RENAME,
    MUST_SELECT_BEFORE_FILL, MUST_SELECT_BEFORE_STROKE, MUST_SELECT_ONLY_ONE, MUST_INSERT_TEXT, CANT_ZOOM_MORE,SAVE_SELECT,SAVE_PROJECT, LOAD,
}
